spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/motor?serverTimezone=UTC
    username: root
    password: 1234
#  main:
#      banner-mode: off # 关闭SpringBoot启动图标(banner)

# mp日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    banner: off # 关闭启动图标


